export const siteConfig = {
  name: "醴陵真好",
  shortName: "醴陵真好网络",
  fullName: "醴陵真好网络传媒有限公司",
  url: "https://412200.net",
  domain: "412200.net",
  getStartedUrl: "#contact",
  ogImage: "https://412200.net/og.jpg",
  description:
    "醴陵真好网络传媒有限公司，14年专注 AI 培训、企业 API 中转、本地 Agent 搭建、FDE 驻场交付与私有化部署，服务企业智能化转型。",
  location: "湖南省醴陵市",
  version: "2026",
  links: {
    email: "mailto:contact@412200.net",
    website: "https://412200.net",
    byteData: "https://bytedata.ai",
    youxiaWucai: "https://youxiawucaici.com",
    hiToys: "https://hi.toys",
  },
  brand: {
    youxiaWucai: {
      name: "醴陵釉下五彩瓷",
      url: "https://youxiawucaici.com",
      wechatAccount: "釉下五彩瓷",
      tagline: "国家级非物质文化遗产 · 数字品牌官网",
    },
    hiToys: {
      name: "Hi.Toys",
      url: "https://hi.toys",
      tagline: "跨境电商独立站 · 潮玩出海",
    },
    shipinhao: {
      name: "醴陵真好视频号",
      wechatSearch: "醴陵真好",
      tagline: "新媒体营销 · 7 天破圈",
    },
  },
  contact: {
    email: "contact@412200.net",
    wechatQrcode: "/wechat-qrcode.png",
    wechatSearch: "醴陵真好",
    location: "湖南省醴陵市",
  },
  stats: {
    clients: "50+",
    years: 14,
    projects: "200+",
    satisfaction: "99%",
    updated: "2026年7月",
  },
  seo: {
    title: "AI培训 · Agent搭建 · 企业API中转 | 醴陵真好网络",
    titleTemplate: "%s | 醴陵真好网络",
    description:
      "提供企业 AI 培训、本地 Agent 搭建、API 中转、FDE 驻场交付、RAG 知识库与私有化大模型部署。14年交付经验，支持远程与上门服务。微信搜一搜「醴陵真好」。",
    keywords: [
      "AI培训",
      "企业API中转",
      "本地Agent搭建",
      "FDE驻场交付",
      "私有化AI部署",
      "RAG知识库建设",
      "AI工作流自动化",
      "大模型微调",
      "AI应用开发",
      "智能客服部署",
      "企业智能化转型",
      "跨境电商独立站",
      "品牌官网建设",
      "湖南AI培训",
      "醴陵AI服务",
      "醴陵真好网络传媒有限公司",
      "醴陵真好",
      "412200.net",
    ],
    areasServed: ["醴陵市", "株洲市", "长沙市", "浏阳市", "湖南省"],
  },
};

export type SiteConfig = typeof siteConfig;
